### ISSUE TITLE
Awesome req / reqi xptemplate not working on windows

### ISSUE THREAD

**Issue by mklabs** [torgeir/vim#2]
Hi!

First off, thanks for your video (https://www.youtube.com/watch?v=-uyhOUSFgGw) and this repository.

I wanted to use this particular snippet but got stuck with my Windows / Onivim setup not recognizing `basename`. I fixed it with using `node -pe`. I thought I would add an issue here to discuss about it and propose a fix.

Here is my suggested fix:

```vim
" strip directory portion of a pathname
function! s:f.strip_path(pathname)
  if has('win32')
    return substitute(system("node -pe \"require('path').basename('" .  shellescape(a:pathname) . "')"), "\n", "", 'g')
  else
    return substitute(system("basename " .  shellescape(a:pathname)), "\n", "", 'g')
  endif
endfunction
```

While I could fork the repo and submit a PR to fix it, I wanted to open up this issue before doing so, in case you're not interrested.

This brings my second question: if by any chance you're interested, would you consider putting these xptemplate snippets into their own dedicated repository ? If so, I would definitely use them ^^ Meanwhile, I'm going to do the same.

**Comment by torgeir** [comment]
Hey, you're welcome! Glad you enjoy it.

I don't really know of any other viable solutions for finding the basename of a path in a cross os way either. I usually default to python for this, but node will probably work fine as well! And its an easy install. 

I'll definitely merge a PR with this if you submit one! I don't maintain this repo as frequently any longer, but still default to installing it wherever I go, so I'll be happy to merge it. As for a separate repository, feel free take it and create a repo yourself! I don't intend too, as I want be giving any guarantees for keeping them up to date with new xptemplate version etc 😅

**Comment by mklabs** [comment]
Hey ;) Thanks for the answer.

I managed to get it working with node, even though it's not a perfect solution (a little bit slow but still managable): https://github.com/mklabs/vimfiles/blob/master/ftplugin/javascript/node.xpt.vim

Okay then, I'll prepare a little PR for you ^^ If you're not using Windows, the interest is limited but still you may one day 😃 PR coming this week I feel like, today and tomorrow will be short in term of time.

As for the repo, fair enough, I understand. I want to do this myself, for now, I did it in my vimfiles repository. I may end up outsourcing it in a plugin repository, I'll prefer to do so eventually. You'll get full credits for your node require gem.

**Comment by mklabs** [comment]
From now on, I'll be watching your repo, in case you come up with another awesomeness regarding xptemplate (not many users for now for this) or vim in general.

**Comment by torgeir** [comment]
If you have python installed, check if something like `python -c 'import os;print os.path.basename("/some/file")'` speeds things up

Go for it! 👍

**Comment by mklabs** [comment]
It's not like I don't like python but .. node is more portable to me (js dev) and not sure how python goes with Onivim and Windows, it's usually kind of a pain to setup. The node solution is good enough for me for the moment, I said it was a bit slow but it's still fast enough to be usable and very useful 👍 

Thanks for the tips! I may check it anyway.
